### ISSUE TITLE
「Request」Add ArrayList support for configs.

### ISSUE THREAD

**Issue by Dylan773** [jdngray77/HTMLDesigner#29]
## Main Goals : 
 - Support ArrayList data type for project configurations.

## Desired API
 - Enum values support ArrayList data type.

**Comment by jdngray77** [comment]
doable with caveats.

I will not be able to store or verify the data type of the array, unless i change the enum naming convention to include it - which i also don't want to do.

So you'll be responsible for making sure that the data type put into and casted out of the registry is always the correct one.
